name: Build Mesa Turnip for Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Mesa from GitLab
      run: |
        git clone https://gitlab.freedesktop.org/mesa/mesa.git
    
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-mako meson ninja-build \
          bison flex libdrm-dev libexpat1-dev \
          libzstd-dev zlib1g-dev llvm clang \
          libwayland-dev wayland-protocols \
          cmake pkg-config glslang-tools

    - name: Download Android NDK r28
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r28-linux.zip
        unzip android-ndk-r28-linux.zip
        mv android-ndk-r28 $HOME/ndk

    - name: Prepare cross file
      run: |
        echo "[binaries]"                          >  cross-file.txt
        echo "c = 'aarch64-linux-android21-clang'" >> cross-file.txt
        echo "cpp = 'aarch64-linux-android21-clang++'" >> cross-file.txt
        echo "ar = 'llvm-ar'"                      >> cross-file.txt
        echo "strip = 'llvm-strip'"                >> cross-file.txt
        echo "pkg-config = 'pkg-config'"            >> cross-file.txt
        echo ""                                    >> cross-file.txt
        echo "[host_machine]"                      >> cross-file.txt
        echo "system = 'android'"                  >> cross-file.txt
        echo "cpu_family = 'aarch64'"              >> cross-file.txt
        echo "cpu = 'aarch64'"                     >> cross-file.txt
        echo "endian = 'little'"                   >> cross-file.txt

    - name: Set environment variables for NDK
      run: |
        echo "NDK=$HOME/ndk" >> $GITHUB_ENV
        echo "PATH=$HOME/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH" >> $GITHUB_ENV

    - name: Configure Meson
      working-directory: mesa
      run: |
        meson setup build-android \
          --cross-file ../cross-file.txt \
          -Dplatforms=android \
          -Dllvm=enabled \
          -Dshared-llvm=enabled \
          -Dbuildtype=release \
          -Dvulkan-drivers=freedreno \
          -Dgallium-drivers=llvmpipe \
          -Dprefix=/mesa-install

    - name: Build Mesa
      working-directory: mesa
      run: |
        ninja -C build-android

    - name: Install Mesa
      working-directory: mesa
      run: |
        ninja -C build-android install

    - name: Package into ZIP
      run: |
        cd mesa-install
        zip -r ../mesa-turnip-android.zip .

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mesa-turnip-android
        path: mesa-turnip-android.zip

    - name: Create Release and Upload ZIP
      uses: softprops/action-gh-release@v1
      with:
        files: mesa-turnip-android.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
